---
title: "Potato Salad"
output: html_notebook
---

```{r}
if(!require(pacman))install.packages("pacman")
pacman::p_load('tidyr', 'skimr', 'parsedate', 'lubridate', 'ggplot2', 'dplyr', 'bbplot', 'sugrrants', 'tsibble', 'viridis')
```

```{r}
setwd("~/Development/potato-salad")
```

```{r}

df <- read.csv("~/Development/potato-salad/df.csv", stringsAsFactors=FALSE)
df$posixct <-parse_date(df$PlayedAt)
df$date <- date(df$posixct)
df$weekday <- weekdays(df$posixct)
df$monthAndYear <- format(df$posixct, "%Y-%m")
df$hour <- hour(df$posixct)
potato.df <- df[df$Id == '1jzIJcHCXneHw7ojC6LXiF',]
# 1jzIJcHCXneHw7ojC6LXiF
```

```{r}
df %>% 
  group_by(Id) %>%
  summarise(n = n()) %>%
  arrange(desc(n))
```

```{r}
df.after.first.potato <- df[df$date >= '2018-10-12',]

df.after.first.potato%>%
  group_by(Id) %>%
  summarise(n = n()) %>%
  arrange(desc(n))
```


```{r}
# of all my songs how many are potato salad
(nrow(df[df$Id == '1jzIJcHCXneHw7ojC6LXiF',]) / nrow(df)) * 100
```
```{r}
(nrow(df.after.first.potato[df.after.first.potato$Id == '1jzIJcHCXneHw7ojC6LXiF',]) / nrow(df.after.first.potato)) * 100
```


```{r}
# songs listened in a row
history.rle <- rle(df$Id)
rle.df <- data.frame(tapply(history.rle$lengths, history.rle$values, max))
colnames(rle.df) <- c("values")
rle.df$song <- rownames(rle.df)
rownames(rle.df) <- c()
rle.df <- data.frame(song = rle.df$song, values = rle.df$values)
```

```{r}
daily.potato <- potato.df %>%
  group_by(date) %>%
  summarise(n=n()) %>% mutate(date = as.Date(date)) %>%
  complete(date = seq.Date(min(date), max(date), by="day"))
daily.potato[is.na(daily.potato)] <- 0
```

```{r}
potato.calendar <- daily.potato %>%
  frame_calendar(x = 1, y = 1, date = date, calendar = "monthly")

potato.calendar$n[potato.calendar$n > 0] <- 1

p <- potato.calendar %>%
  ggplot(aes(x = .x, y = .y)) +
  geom_tile(aes(fill = as.factor(n)))
prettify(p, label = "label", label.padding = unit(0.2, "lines"))
```

```{r}
# number of potato days
sum(potato.calendar$n) / nrow(potato.calendar) * 100
```

```{r}
potato.df$weekday <- factor(potato.df$weekday, levels=c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))
potato.hourly.weekly <- potato.df %>%
  group_by(hour, weekday) %>%
  summarise(n = n())

ggplot(potato.hourly.weekly, aes(hour, weekday)) +
  geom_point(aes(color = potato.hourly.weekly$n))  +
  scale_colour_gradientn(colours = terrain.colors(7)) 

```

## Probability of listening to Potato one a weekday
```{r}
weekdays <- df %>%
  select(date,weekday) %>%
  unique() %>%
  group_by(weekday) %>%
  summarise(AmountWeekdays = n())

potato.by.weekday <- potato.df %>%
  group_by(weekday) %>%
  summarise(AmountPotatoWeekday = n())


potato.probs.weekday <- merge(potato.by.weekday, weekdays, by = c('weekday'))
potato.probs.weekday$percentage <- (potato.probs.weekday$AmountPotatoWeekday / potato.probs.weekday$AmountWeekdays)


potato.probs.weekday.clean <- potato.probs.weekday %>%
  select(weekday, percentage)

potato.probs.weekday.clean <- potato.probs.weekday.clean %>%
  arrange(weekday)

```

## Probability of listening to Potato one a weekday at a particular time range
```{r}
# how many hours there are present in the dataset, for example the time X appears Y times
hours <- df %>%
  select(date,hour) %>%
  unique() %>%
  group_by(hour) %>%
  summarise(AmountHours = n())

potato.by.hour <- potato.df %>%
  group_by(hour) %>%
  summarise(AmountPotatoPerHour = n())

potato.probs.weekday.hour <- merge(potato.by.hour, hours, by = c('hour'), all.y = TRUE)
potato.probs.weekday.hour[is.na(potato.probs.weekday.hour)] <- 0
potato.probs.weekday.hour$percentage <- 
  (potato.probs.weekday.hour$AmountPotatoPerHour / potato.probs.weekday.hour$AmountHours)
potato.probs.weekday.hour.clean <- potato.probs.weekday.hour %>%
  select(hour, percentage)
```

```{r}
data.frame(outer(potato.probs.weekday.hour.clean$percentage, potato.probs.weekday.clean$percentage, FUN = "*"))
potato.final.probs <- data.frame(tcrossprod(potato.probs.weekday.clean$percentage, 
                                            potato.probs.weekday.hour.clean$percentage) * 100)

colnames(potato.final.probs) <- 0:23
rownames(potato.final.probs) <- levels(potato.probs.weekday.clean$weekday)
```

```{r}
potato.training <- potato.df %>%
  select(weekday, hour)
potato.training$weekday <- as.numeric(potato.training$weekday)
potato.training$listened <- as.factor(1)
```

```{r}
write.csv(potato.training, file = 'potato_df_weekday_hour.csv', row.names = FALSE)
```

-------------

## Probability of listening to Potato one a weekday AFTER FIRST POTATO DAY
```{r}
weekdays <- df.after.first.potato %>%
  select(date,weekday) %>%
  unique() %>%
  group_by(weekday) %>%
  summarise(AmountWeekdays = n())

potato.by.weekday <- potato.df %>%
  select(date,weekday) %>%
  unique() %>%
  group_by(weekday) %>%
  summarise(AmountPotatoWeekday = n())


potato.probs.weekday <- merge(potato.by.weekday, weekdays, by = c('weekday'))
potato.probs.weekday$percentage <- (potato.probs.weekday$AmountPotatoWeekday / potato.probs.weekday$AmountWeekdays)


potato.probs.weekday.clean <- potato.probs.weekday %>%
  select(weekday, percentage)

potato.probs.weekday.clean <- potato.probs.weekday.clean %>%
  arrange(weekday)

```

## Probability of listening to Potato one a weekday at a particular time range
```{r}
# how many hours there are present in the dataset, for example the time X appears Y times
hours <- df.after.first.potato %>%
  select(date,hour) %>%
  unique() %>%
  group_by(hour) %>%
  summarise(AmountHours = n())

hours <- rbind(hours, c(2,0))

potato.by.hour <- potato.df %>%
  group_by(hour) %>%
  summarise(AmountPotatoPerHour = n())

potato.probs.weekday.hour <- merge(potato.by.hour, hours, by = c('hour'), all.y = TRUE)
potato.probs.weekday.hour[is.na(potato.probs.weekday.hour)] <- 0
potato.probs.weekday.hour$percentage <- 
  (potato.probs.weekday.hour$AmountPotatoPerHour / potato.probs.weekday.hour$AmountHours)
potato.probs.weekday.hour.clean <- potato.probs.weekday.hour %>%
  select(hour, percentage)
potato.probs.weekday.hour.clean[is.na(potato.probs.weekday.hour.clean)] <- 0

```

```{r}
potato.final.probs <- data.frame(tcrossprod(potato.probs.weekday.clean$percentage, 
                                            potato.probs.weekday.hour.clean$percentage) * 100)

colnames(potato.final.probs) <- 0:23
rownames(potato.final.probs) <- levels(potato.probs.weekday.clean$weekday)
```

```{r}
potato.training <- potato.df %>%
  select(weekday, hour)
potato.training$weekday <- as.numeric(potato.training$weekday)
```

```{r}
write.csv(potato.training, file = 'potato_df_weekday_hour_new.csv', row.names = FALSE)
```
